### PR TITLE
doFix

### PR DESCRIPTION
**Pull request by lutzbickhardt**
comments are in the fix

### CODE REVIEW

**Comment by jas-** [comment]
@lutzbickhardt While I appreciate the `pr` can you please re-create it to conform to the `contributing` section? In particular the `pr` is named `doFix`, this is not really indicative of what it fixes. Also the comments are not the place for the description of the `pr`. Thanks.

**Comment by lutzbickhardt** [comment]
Hi Jason,


I am totally lost! I do not understand your "contributing section" and googling "contributing<https://github.com/blog/1184-contributing-guidelines>?" I find:

-> https://github.com/blog/1184-contributing-guidelines


Surely you do not want me to ask you to update your work by creating a file called CONTRIBUTING ?!?


Whatever, I was just trying to point out something in your code that I perceive to being an error and a misleading statement that is overwritten in the next line. Why not fix it yourself?


Cordialement

--------------------------
Lutz BICKHARDT
lutz@bickhardt.fr

NEW COORDINATES !!!
(privat) Graumannsweg 42, D-22087 Hamburg, Germany
(Büro)  Borselstr. 3 - 7 (im Hof), D-22765 Hamburg, Germany

SKYPE: bickhardt

+49 172 3846086 (deutsches Handy / German cell phone)
+49 40 22758122 (privat Hamburg)
+49 40 39190921 (Büro Hamburg)
+33 6 18386906 (portable francais/ French cell phone)
________________________________
De : Jason Gerfen <notifications@github.com>
Envoyé : samedi 18 juillet 2015 17:16
À : jas-/node-libnmap
Cc : Bickhardt, Lutz
Objet : Re: [node-libnmap] doFix (#13)


@lutzbickhardt<https://github.com/lutzbickhardt> While I appreciate the pr can you please re-create it to conform to the contributing section? In particular the pr is named doFix, this is not really indicative of what it fixes. Also the comments are not the place for the description of the pr. Thanks.

-

**Comment by jas-** [comment]
Perhaps you are confused about [OSS](https://guides.github.com/activities/contributing-to-open-source/) as a whole.

To clarify; I am not asking you to create a 'contributing' file. I am however asking you to rename the title of your 'pr' to something a bit more descriptive than 'doFix'.

The reason I ask this is because as you use git workflows it is nice to look at 'git log' and know what pull request and commit message addresses what code revision occurred.

**Comment by jas-** [comment]
Module has been updated to `v0.2.2`. Currently there is no `discover` method available in the latest release. It may be brought back if enough people request it but as it stands now this issue is resolved. Thanks for pointing it out.

**Pull request closed without merging**
