### PR TITLE
Stop -oX - flag being added if it already exists

### PR DESCRIPTION
**Pull request by ckiely91**
Fixes a minor issue I was seeing where the '-oX -' flag was being added multiple times.

### CODE REVIEW

**Comment by jas-** [comment]
Can you provide a use case where this occurs?

**Comment by jas-** [comment]
This made it into `v0.2.29`. Thanks!

**Comment by ckiely91** [comment]
Cheers, sorry I didn't end up providing the use case but I couldn't replicate it in a test project, only happens in my code for some reason and I can't put up all of that. Can't hurt to add the extra check though. :smile: 

Did you end up managing to replicate it?

**Comment by jas-** [comment]
I could not replicate the issue but the check didn't cause failures either. Thanks for the contribution!

**Pull request merged**
