### PR TITLE
Replace CLI Parser with XML Parser

### PR DESCRIPTION
**Pull request by mrzmyr**
#### Features
- Using the XML Output of `nmap` for the `scan` method
- Remove makefile as test dependency
- Make test working with mocks
- Add examples for `scan` and `discover`

### CODE REVIEW

**Comment by jas-** [comment]
Are you familiar with how to `[rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing)` to `[squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)` a `PR`? I would prefer a `pr` that merges one commit to one branch vs. many as in the event of a rollback it would make it much easier to accomplish without a lot of fuss.

**Comment by mrzmyr** [comment]
There you go :)

**Comment by jas-** [comment]
Thanks give me some time to review

**Comment by jas-** [comment]
What is the actual purpose of the fixtures for the test cases? Are they needed? I would prefer to not have them included.

Would you also be able to remove the '$' element references in the json output?

**Comment by mrzmyr** [comment]
How would you like to run tests in CI when you remove the fixtures ?

Can you give me an example for the '$' reference ?

**Comment by jas-** [comment]
When a scan or discover is performed we really aren't concerned with what details of the scan are returned because using each persons system for the scan is going to give the tests varying results. We only care that the object returned is valid and contains valid elements.

In regards to using '$' within the XML to JSON conversion;

```json
{
    "$": {
        "scanner": "nmap",
        "args": "nmap -oX - -T5 -p80,443 10.12.20.97-128",
        "start": "1438608336",
        "startstr": "Mon Aug  3 15:25:36 2015",
        "version": "6.47",
        "xmloutputversion": "1.04"
    },
```

For whatever reason it adds "$" for some sections that relate to the scan or command run. I am assuming this is because the XML schema or DTD doesn't name those? And if not can we replace them with strings for easier reference within the JSON object?

**Comment by mrzmyr** [comment]
I thought the same about the different environments, thats exactly the reason why I brought in fixtures. To just confirm that the parser is working correctly.

The '$' information is, as you guessed, some xml meta data, yep. We can parse them out if you'd like to. Let me check that later today.

**Pull request merged**
